# $HOME/.config/straship.toml

# Disable the blank line at the start of the prompt
add_newline = false

# disable the line break for the prompt.
# if you are using a twoline prompt, set 
# disable = false, or the prompt breaks.
[line_break]
disabled = true

#Prompt format for one line prompt.
format = """ $directory$git_status$git_commit$cmd_duration
](bold green)
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# change the prompt character from 
# unicode to ascii.
[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[>](bold green)"

#Set the username.
[username]
style_user = "bold green"
 style_root = "bold red" 
show_always = true
format = "[$user]($style)"

# Set the machine host name.
[hostname]
ssh_only = false
#style = "bold yellow"
format = "@[$hostname](bold yellow):"

# Set the directory path.
# Truncation length should be set
# if you want to save space on the
# terminal.
[directory]
truncation_length = 1
truncation_symbol = "../"
style = "bold blue"
format = "[$path]($style)[$lock_symbol]($lock_style) "

#Set the git branch
[git_branch]
format = "[$branch]($style) "
style = "bold yellow"

# Set the git status.
# it is commented as it is a work in progress.
#[git_status]
#ahead = "⇡${count}"
#diverged = "⇕⇡${ahead_count}⇣${behind_count}"
#behind = "⇣${count}"
#modified = "!"
#staged = "+"
#deleted = "✘"

# Set how long it takes for commands to 
# execute.
[cmd_duration]
min_time = 5_000  # Show command duration over 1,000 milliseconds (=10 sec)
format = "[$duration]($style) "

# Set the shell indicator for the prompt.
# This should tell you which shell you are 
# running starship on.
[shell]
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
powershell_indicator = "❯_"
disabled = false
format = "[$indicator](bold red)"

#Disable all packages.
[package]
disabled = true

[python]
disabled = true
